### ISSUE TITLE
読み上げ位置まで強制的にスクロールする機能がうまく機能していません

### ISSUE THREAD

**Issue by szk24** [limura/TabSpeech#1]
読み上げている音声と読み上げ位置を強制スクロールする機能がズレます。

強制スクロールが止まり止まりで、音声が先に行ってしまいます。
音声の速さは1.99です。

昨日までは正常に機能していました。
Cookieや閲覧履歴等を削除してみたのですが、直りませんでした。

こちらのPCの問題でしょうか？

**Comment by limura** [comment]
その情報からだけではなんとも言えませんね。

こちらで同様の問題が発生しないかを試したいので使っている環境や設定等を詳しく教えていただけますか？

・利用中のOSとそのOSのバージョン
・Chromeのバージョン
・TabSpeechのバージョン
・TabSpeechの設定項目の全て(画面キャプチャでも設定項目の全てがわかれば何でも良いです)
・問題の再現手順等
　・問題の起こったURL
　・読み上げ開始をする開始点(マウスなどで選択する場所又はリロード直後等開始点が特定できる情報)
　・問題の起こる場所(いつも同じ場所でズレが生じるのか、そうではないのか等も含む)
　・問題の起こる頻度(10回中10回なのか、2,3回なのか)
　等、再現に必要だと思われる情報全て

なお、スクロールが止まり止まり、という表現からしますと、何らかのの重たい処理が走っているか何かで処理が追いついていないような雰囲気を感じます。
Chromeのタスクマネージャ( https://www.atmarkit.co.jp/ait/articles/1601/22/news029.html ) やOS側の負荷測定ができそうな物(Windowsならタスクマネージャ、macOSならアクティビティモニタ)で高負荷になっている物があったりしないかを確認しても良いかもしれませんね。

また、TabSpeech は Cookie や閲覧履歴は使っておりませんのでその辺りを削除しても何も変わらないと思います。

**Comment by szk24** [comment]
![tabspeech](https://user-images.githubusercontent.com/15940018/124699576-03c62280-df26-11eb-874e-79b5fb844d55.jpg)

・利用中のOSとそのOSのバージョン
windows10 Home　64bit
バージョン21H1
メモリー8GB

・Chromeのバージョン
Microsoft Edge バージョン 91.0.864.64 (公式ビルド) (64 ビット)
Google Chrome　バージョン: 91.0.4472.124（Official Build） （64 ビット）
GoogleChromeは、「開始」ボタンを押しても動きません。読み上げていかないです。
Microsoft Edgeは昨日まではちゃんとスクロールしていました。

・TabSpeechのバージョン
どこから確認できますか？

・TabSpeechの設定項目の全て(画面キャプチャでも設定項目の全てがわかれば何でも良いです)



・問題の再現手順等
　・問題の起こったURL
https://ncode.syosetu.com/n4830bu/135/

　・読み上げ開始をする開始点(マウスなどで選択する場所又はリロード直後等開始点が特定できる情報)
サイトのページの初めから

　・問題の起こる場所(いつも同じ場所でズレが生じるのか、そうではないのか等も含む)
どこの位置から読み上げを始めてもスクロールが止まりとまりになって音声からズレていく。　

・問題の起こる頻度(10回中10回なのか、2,3回なのか)
10回中10回

重い処理が動いているかと思い、もう一つの別のPCで動かしてみました。
MicrosoftEdgeの方は、スクロールが止まり止まりで音声からズレていきます。
こちらもGoogleChromeの方は、「開始」を押しても動きません。
この別のPCは、windows10 Home 64bit バージョン 20H2
MicrosoftEdgeもGoogleChromeも上に書いたバージョンと同じです。
こっちのPCは、メモリーは16GBです。

　等、再現に必要だと思われる情報全て

読み上げているページの問題かと思い、別のページも読み上げてみましたが、同じように音声とズレていきます。
別のページ(https://ncode.syosetu.com/n4830bu/134/)

昨日まではスクロールしていたので、再現に必要な情報はちょっと見当が付きません。

他のWebサイトでも「開始」を押しても、読み上げないサイトがあります。
EdgeでもChromeでも読み上げないです。
Yahooメールとかニコニコチャンネルとかです。

他に必要な情報があれば仰って下さい。わかる範囲でお答えします。

お手数おかけします。

**Comment by szk24** [comment]
追記になります。

MicrosoftEdgeの方ですが、PC2台で同期していたのを解除しましたら、強制スクロールが遅れるのは直ったのではないかと思います。今の所、普通に読み上げとスクロールをするようになりました。

GoogleChromeの「開始」を押しても読み上げない方の問題は、
1.同期を解除してTab Speechの「開始」を押す
→読み上げない

2.アカウントをログアウトして、再度Tab Speechを入れて「開始」ボタンを押す
→読み上げない

3.別のアカウントでログインして、再度Tab Speechを入れて、「開始」を押す
→読み上げない

という状態になります。

**Comment by limura** [comment]
ありがとうございます。

こちらの手元の Windows で、 https://ncode.syosetu.com/n4830bu/135/ を使って動作確認してみましたが、
同様の問題を確認することはできませんでした。
なお、こちらの環境では Speaker の設定が DEFAULT では動作しませんでしたので、
ja-JP Microsoft Haruka - Japanese (Japan)
で動作確認しています。

ということで、こちらでは問題を確認できませんでしたので
お知らせいただきました文章から問題を理解する必要が出てきたのですが、
音声とズレていくというのは正確にはどういう事なのかがよくわかりませんでした。
「スクロールが止まり止まり」であるという事と「音声が先に行く」という事は書いてあるのですが、
「スクロール」が何を意味しているのかがよくわかりません。
動画にでも撮って説明していただければわかりますかね？

なお、既知の問題として、macOS 上の ja-JP Kyoko 等では、アルファベットで書かれた単語(又は英文等)やいくつかの空白に類する文字を読み上げた時に、実際に読み上げられている声と、読み上げ位置を示している選択範囲がズレるという事はあるのですが、これと似たような問題の事を仰っているのかもしれないと考えています。
この macOS でのみ確認されている問題は、「読み上げ位置まで強制的にスクロールする」との関連というよりは、読み上げ位置表示自体の問題です。(「読み上げ位置まで強制的にスクロールする」機能は読み上げ位置表示で示されている位置にスクロールしている実装なので、このオプションをONにしていようがOFFにしていようが読み上げ位置表示自体はズレる事で確認できると思います)
この問題は、SpeechSynthesis 側の onboundary イベント
https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance/onboundary
の発火時に報告される読み上げ位置がズレて報告される(ように見える)という事が原因で起こっている問題です。
ただ、何故ズレた位置が報告されるのかがよくわかりません(アルファベットをマルチバイトとして扱うことによるなんちゃらだとか空白のように見える文字を纏めて1文字に数えたり文字数にカウントしなかったりするとかそういうような何かが起こっているような気はしますがよくわかりません)
そのため、話者(Speaker)を変える(発話エンジンを変える)事で(その辺りの読み上げ位置をカウントする部分まで変更されるため、問題が)解消する場合がありそうな気はしますが根本的な解決ではないですね。

次に TabSpeech のバージョン番号は TabSpeech のアイコンを右クリックして「拡張機能を管理」から確認できます。

また、動作しないURLがあるのなら、そのURLについても、一つ前の私の投稿と同様な再現実験に必要な情報を提供いただかない上には何もできませんし、この issue に混ぜるべき案件でもないので別 issue にでもしてください。

他に、Microsoft Edge は対象としていません。私としては対応の予定もありません。

次に、「PC2台で同期していた」というのは何をしていたのでしょうか。TabSpeech には同期するような機能はなかったと思っています。

**Comment by szk24** [comment]
丁寧な説明ありがとうございます。
わかりました。

Tab Speechのバージョンは　1.9.0です。

同期を解除というのは、MicrosoftEdgeやGoogleChromeの同期です。添付した画像の赤枠の部分の「同期は有効です」というのでわかりますでしょうか。
![douki](https://user-images.githubusercontent.com/15940018/124837982-e2fedb00-dfc0-11eb-86bb-48a43a56ba19.jpg)

Tab Speechではなく、ブラウザ自体の同期です。2台のPCそれぞれで、MicrosoftEdgeで同期していたら、選択範囲と音声がズレていきました。片方のPCのブラウザの同期を解除したら直りました。

選択範囲と音声のズレというのは
例えば、

あいうえお
かきくけこ
・・・
まみむめも
やゆよ
わ
ん
・・・
ABC
DEF
GHI
・・・
XYZ

という文章があって、選択範囲が「あいうえお」の部分にあるのに、音声自体が「わ」の部分にあり、どんどん選択範囲と音声が離れていき、「かきくけこ」を選択範囲の時には、音声は「GHI」に行っていて、どんどん選択範囲と音声がズレて離れてきます。
強制スクロールにチェックを入れていても、選択範囲が「かきくけこ」なので、音声がブラウザの表示している画面外の「GHI」にいっていても、スクロールが追いついていかない感じです。
この説明でわかりますでしょうか。

issueを混ぜてしまい申し訳ありません。
GoogleChromeの動かないというのも教えて頂いたのを試してみました。
ja-JP Microsoft Haruka - Japanese (Japan)
で動きました。
ありがとうございました。

お手数おかけしました。

issueする際に、再現するための情報が書けるように精進します。

P.S.
安くて申し訳ありませんが、私もじゃり豆が好きなので、じゃり豆を贈らせて頂きました。
昨日注文しましたので、今日には届くかと思います。

**Comment by limura** [comment]
ありがとうございます。

なるほど症状としては macOS 側で発生している問題と似ている問題のようですね。
ただ、macOS 側の Kyoko等 とは挙動が違うようだという所と、話者を Microsoft Haruka に変えると解消するという所からすると、音声合成エンジン側の差異が大きく関与しているっぽいですね。

なお、macOS の Kyoko等 で https://ncode.syosetu.com/n4830bu/135/ を読み上げさせた時は、このページのアルファベットや空白に類する文字が少ないため、ほとんどズレは生じません。
今手元の macOS で実験したところ、上記のURLを最初から(タイトルの「冬籠りと冬の手仕事」の部分から)読み上げ始めて最後まで読み上げさせようとした時、最後の文字に読み上げ位置表示が移動した時に実際に読み上げられていた物との文字数的な差は12〜14文字位でした。

具体的には、最後の行の

  次回は、神官長とカルステッドとベンノの三者会談（＋マイン）です。

の部分の末尾の「です。」が選択された状態になった時に読み上げられていたのは「ベンノ」の部分でした。

また、お寄せ頂きました内容からしますと、そちらで確認できているズレは向きが逆？のようで、
選択範囲よりも読み上げられている部分の方が先のようですね。
(例示されている物は「あいうえお」を選択中に「わ」を読み上げているという事なので)
読み上げられている部分の方が選択範囲よりも先に行ってしまう、という症状はこちらでは確認したことがありませんので、こちらの手元で同様の状況を再現できないのが残念です。

次に、Chrome の同期の機能のON/OFFで挙動が変わるという症状なのですが、同期が関与する部分が想像できませんでした。
といいますか、TabSpeech 側で Chrome の同期機能によって変わる挙動はないはずなのです。
設定項目内の Speaker に設定できる話者(音声合成エンジン)は各OSやマシン毎に違いますため、どこか一つのマシン上でしか使えない設定が同期されてしまうと、他のマシンでは利用不可能な話者設定になってしまう可能性があるために、意図的に同期をしないストレージを使って設定を保存している(chrome.storage.sync は使わずに chrome.storage.local を使っている)ためです。逆に言いますと、もし設定が同期されているとしたら何処かで実装ミスをしている事になります。
一応、手元に 2台 の Windows PC を用意して簡単な同期テストをしてみましたが、設定項目の同期はされていなさそうでした(同期された事を確認するのは簡単なのですが、同期されない事を確認するのは面倒くさいので確実とは言えなさそうな方法でしか確認できていません)。
と、いう事なので、Chrome の同期の仕組みによって挙動が変わるというのもいまいちよくわかりません。
Speaker が DEFAULT DEFAULT で動作していた所からすると、Chrome 本体側の設定で SpeechSynthesis の使う default voice が変化したりする事はありそうな気はしますけれども、どこの設定項目が関与するのかはよくわかりません。
ただ、話者側の問題なのであれば、個々のマシンにおいて TabSpeech 側の設定で Speaker を問題が発生しにくい話者(Microsoft Haruka等)に設定しておくことで回避はできそうな気がします。

どうにしても、Speaker の設定で回避はできたとしても根本的な問題の解決ではないのでなんとかしたい所ですが…… 手元で再現できないことには私の所では対応は難しいですね。こちらでは DEFAULT だと発話自体できないんですよ……

あと、じゃり豆ありがとうございます。先ほど届きました。息抜きの時間等に楽しませていただきます。ヾ(*´∀｀*)ノｱﾘｶﾞﾄｳｺﾞｻﾞｲﾏｽｰ

**Comment by szk24** [comment]
詳しい説明ありがとうございました。

えぇっと、役に立つかわかりませんが、補足になります。
2台のPCのうち、今まで1台目でTab Speechを動かしていました。
1台目のPCで別作業をするため、2台目のPCでTab Speechを使用しました。
使ったその日は、問題なかったのですが、次の日、PCを起動し、Tab Speechを利用したらズレが生じるようになりました。
で、同期を解除しましたら、普通に動くようになりました。

じゃり豆喜んでいただけて良かったです。楽しんでください。m(＿)m

**Comment by limura** [comment]
補足ありがとうございます。

前述の通り同期周りで何が変わるのかがわかっておりませんので推測する事しかできないのですけれども、仮に、発話に利用されている「話者」(TabSpeech の設定における Speaker の欄で設定される物。Microsoft Haruka等)を変化させた時に同様の問題が発生するのであれば、Chrome の同期を行う事で DEFAULT DEFAULT で選択される話者が変化した事によるものだと仮定してしまって良さそうな気もしています。

という事で、

1. 問題の発生したPC(2台目のPC)で問題なく動作していた時の声質
2. 問題の発生したPCでズレが生じてしまっていた時の声質
3. 問題の発生したPCで状況が改善した時の声質

のそれぞれを「聞き分けて」どの「話者」であるのかが確認できるのなら、2. でズレが生じてしまう声質の設定を「ja-JP」の中から探し出す事で、同様の問題がどこでも再現できるようになるかもしれないような気はしています。

ただ、こちらの Windows 環境で選択できる Voice は Microsoft 系の4つと Google日本語 の計 5種類 だけなので、その中で問題の動きをするものを探したほうが早そうです。
ということで全ての話者について確認してみたのですが、どうやら Microsoft 系の4つは正しく動作していて、Google日本語 は onboundary イベント自体が発生していないようでした。
onboundary イベントが発生しない場合は読み上げている位置を知る(更新する)すべがありませんので、選択範囲が移動する事もスクロールもしません。これはこれで問題なので、onboundary イベントが発生しない原因を突き止める必要がありそうなのですが…… Microsoft 系の物では同じ使い方で動いている(し、以前は Google日本語 でも動いていたと思われる)ので、Google日本語 の側の問題なのではないかなぁという気がしてしまっています。(ただ、そうだとして、どこに不都合報告をするとうまく動いてくれるのかよくわからないという問題もありますね)

という訳なので、今回の問題を発生させる原因が話者によるものであり、その話者は何であるのかがわかったとしても、こちらの環境では再現は難しそうですね。うーむー。

**Comment by szk24** [comment]
丁寧に対応して下さりありがとうございました。
Closeをしなければならないのですね。
ありがとうございました。
