### ISSUE TITLE
Google Chromeで、Tab Speechが動かないです。

### ISSUE THREAD

**Issue by szk24** [limura/TabSpeech#2]
Google Chromeで、3,4日前からTab Speechが動かないです。

Speakerを「DEFAULT」と「ja-JP」両方行ってもダメでした。

小説家になろうというサイトがダメなのかと思い、Yahooのトップページでもやってみたのですが、動作しませんでした。

**Comment by limura** [comment]
どのように動かないのでしょうか。

以下のような点が明らかになっていると助かります。

- 使用している TabSpeech の バージョン(manifest.json を確認してください。現時点で最新のものは 2.0.5 です)
- 使用しているOS
- 使用しているChromeのバージョン
- 問題を発生させるために必要な情報(問題が発生するURL、問題を発生させる時の操作方法、どうなってほしかったか、実際はどうなったか、TabSpeech の設定(画面キャプチャでも良いです)、他に思いつくことはなんでも)
- 問題が起きた時のコンソールログで怪しそうなもの(content scriptのものや、Service Worker, speechSynthesis.htmlのもの)

最後のコンソールログについては、例えば以下のようにすると確認できます。

content script のもの：
Google Chromeのメニュー(右上辺りにある上下に3つの点があるアイコンのもの)→その他のツール→デベロッパーツールでデベロッパーツールを開いてそのデベロッパーツール側のメニュー(右上辺りにある上下に3つの点があるアイコンのもの)→コンソール ドロワーを表示

Service Worker, speechSynthesis.html：
Google Chrome の TabSpeech アイコンを右クリック→拡張機能を管理で開いたページ内の「ビューを検証」にあるそれぞれへのリンクを選択

**Comment by szk24** [comment]
必要な情報を教えていただきありがとうございます。
以下に記載します。


・使用している TabSpeech の バージョン　2.0.2 (拡張機能を管理から確認)

・使用しているOS　Windows10

・使用しているChromeのバージョン
バージョン: 128.0.6613.120（Official Build） （64 ビット）

・問題を発生させるために必要な情報(問題が発生するURL、問題を発生させる時の操作方法、どうなってほしかったか、実際はどうなったか、TabSpeech の設定(画面キャプチャでも良いです)、他に思いつくことはなんでも)

https://ncode.syosetu.com/n7787eq/510/

https://kakuyomu.jp/works/1177354054885201112/episodes/1177354054885745831

https://www.yahoo.co.jp/

上記のサイトでTabSpeechを作動させようとして、読み上げが始まらなかったです。

TabSpeechの「開始」ボタンを押すのですが、読み上げが始まらないです。

TabSpeechの「設定」からResetして初期値でSaveして再度試してみたのですが、読み上げないです。

それと、TabSpeechの最新バージョンが2.0.5とのことですので、Chromeから削除して、再度TabSpeechを入れなおし、バージョン確認したのですが、何故か2.0.5にならず、2.0.2のままです。
https://chromewebstore.google.com/detail/tabspeech/ccojlmmbakjcoddbepmmogiobbmmhmjc?hl=ja
このサイトからTabSpeechを入れなおしました。
このサイトだとバージョンが2.0.2なのですが、2.0.5にアップデートするにはどうすればよいでしょうか？


以前、読み上げが始まらなかった時に「設定」からSpeakerを変更したら動いたので、「ja-JP」の音声変更をしたのですが、どれに変更しても読み上げが始まらなかったです。



・問題が起きた時のコンソールログで怪しそうなもの(content scriptのものや、Service Worker, speechSynthesis.htmlのもの)

Consoleをひらいてみました。
出ている表示は一つだけです。

Failed to load resource: the /limura/TabSpeech/issue_comments/2340103401/edit_form?textarea_id=issuecomment-2340103401-body&comment_context=:1 server responded with a status of 403 ()


情報の書き方がよくわかっておらず、下手な説明で申し訳ありません。
足りない情報があれば再度聞いていただけますと助かります。

よろしくお願いいたします

**Comment by limura** [comment]
詳しい情報ありがとうございます。

こちらの手元のWindows11で 2.0.2 を使って試してみているのですが、https://www.yahoo.co.jp/ 以外では同様の挙動が確認できていません。
ただ、https://www.yahoo.co.jp/ については読み上げ開始位置を選択(読み上げさせたい開始位置を範囲選択)していない状態ですと発話ができないサイトになりますので、単純に https://www.yahoo.co.jp/ を開いて「開始」を選択しただけでは発話が始まらないのは(一応)問題ではないと考えています。

次に、設定を一旦 Reset したとのことなのですが、リセットされた後に Test で発話できることは確認されましたでしょうか。
Windows10 が手元に無いので確認できないのですが、場合によっては DEFAULT ですと発話が開始されませんので、Reset された後は Test で発話が開始されることを確認してからご利用ください。

次に、コンソールログなのですが、恐らく確認しているページが違いそうです。

手順としては以下のようにしてください。

1. 問題が発生するWebページを開く
2. コンソールログを開く
3. TabSpeech で発話させようとする

示されています情報からしますと、恐らくはこのissueのページを開いているタブで作業していて、TabSpeech で発話させようとして失敗したページではない気がします。

また、恐らくは content script側では問題は起きていないと考えられるため、Service Worker や speechSynthesis.html 側のログを確認したいのでそちらの情報をお願いしても良いでしょうか。

次に、2.0.2 というと Chrome ウェブストア 側で公開されている最新のものですね。
こちら(GitHub側)のものを使うことで 2.0.5 で試せるはずです。
方法としては、

1. GitHub から TabSpeech を clone する
2. Google Chrome で拡張機能のページ( chrome://extensions/ )を開く
3. 右上の「デベロッパーモード」をONにする
4. 左上の「パッケージ化されていない拡張機能を読み込む」を選択
5. 1. で clone したディレクトリの中の TabSpeech のフォルダ(中に manifest.json のあるもの)を選択(TabSpeech\TabSpeech となっているので注意)
6. 恐らくは Chromeウェブストア から取得した TabSpeech と、5. で読み込んだ TabSpeech が別々に表示されるので、利用したくない方のスイッチをOFFにして利用しないようにする

という形で試すことができるはずです。
ただ、こちらの手元の 2.0.2 では同じ問題が確認できていないため、恐らく 2.0.5 で解消するような問題ではなさそうな気がしなくもありません。2.0.5 で解消するような問題であればそれはそれで良いのですが、一応 2.0.2 のどこで問題が発生したのかを確認したいので、問題の起こるバージョン(2.0.2 か、2.0.5でも発生するなら 2.0.5)での Service Worker や speechSynthesis.html 側のログなどが確認できると嬉しいです。

推測としては wedata.net様 からのデータ読み込みで失敗して Service Worker が停止していそうな予感はしていますが。

**Comment by limura** [comment]
あ、TabSpeech を読み込んだ後、既に開いているタブで動作させる場合は、そのタブをリロードしないと content script が読み込まれませんので動作できないため、一応テストを開始する前にはタブをリロードしてからお試しください。

**Comment by szk24** [comment]
2.0.2で読み上げないページでコンソールにでた表示
 
Attestation check for Topics on https://ncode.syosetu.com/ failed. 
Understand this warning
510/:1 Attestation check for Topics on https://ncode.syosetu.com/ failed.


（2.0.5でも開始ボタンを押しても読み上げが始まりません）
2.0.5でリロード後に開始ボタンを押してコンソールにでた表示

373Third-party cookie will be blocked in future Chrome versions as part of Privacy Sandbox.Understand this warning
510/:1 Attestation check for Topics on https://ncode.syosetu.com/ failed.Understand this error
contentScript.js:626 KickSpeech {type: 'KickSpeech', SiteInfoArray: Array(11)}
510/:1 Error in event handler: TypeError: Cannot read properties of undefined (reading 'length')
    at WedataConvertTableToLocalConvertDic (chrome-extension://bacmafblgmncfagnkdocacfkhjknfeni/contentScript.js:440:27)
    at CreateConvertDic (chrome-extension://bacmafblgmncfagnkdocacfkhjknfeni/contentScript.js:455:20)
    at SpeechWithPageElementArray (chrome-extension://bacmafblgmncfagnkdocacfkhjknfeni/contentScript.js:504:20)
    at runSpeechWithSiteInfo (chrome-extension://bacmafblgmncfagnkdocacfkhjknfeni/contentScript.js:601:36)
    at runSpeech (chrome-extension://bacmafblgmncfagnkdocacfkhjknfeni/contentScript.js:611:8)
    at chrome-extension://bacmafblgmncfagnkdocacfkhjknfeni/contentScript.js:627:7



色々質問してしまって申し訳ありません。
Service Worker や speechSynthesis.html 側のログは、どこから確認できますでしょうか？

**Comment by limura** [comment]
検証ありがとうございます。

おぉ。content script側 の問題ですねこれは。
8ea074f にて対応してみました。試してみて頂けますと助かります。

また、Service Worker や speechSynthesis.html 側のコンソールログを確認するには以下のようにしてみてください。

1. Google Chrome の右上に表示されている拡張機能リストの中から TabSpeech のアイコンを右クリック
2. 「拡張機能を管理」を選択
3. 開いたページ内の「ビューを検証」にあるそれぞれへのリンクを選択

**Comment by szk24** [comment]
2.0.5を再度Cloneして入れ直し、リロードして発話してみましたが、読み上げませんでした。

コンソールドロワーの表示
510/:1 Attestation check for Topics on https://ncode.syosetu.com/ failed.Understand this error
contentScript.js:627 KickSpeech Object
510/:1 Error in event handler: TypeError: Cannot read properties of undefined (reading 'length')
    at WedataConvertTableToLocalConvertDic (chrome-extension://bacmafblgmncfagnkdocacfkhjknfeni/contentScript.js:441:27)
    at CreateConvertDic (chrome-extension://bacmafblgmncfagnkdocacfkhjknfeni/contentScript.js:456:20)
    at SpeechWithPageElementArray (chrome-extension://bacmafblgmncfagnkdocacfkhjknfeni/contentScript.js:505:20)
    at runSpeechWithSiteInfo (chrome-extension://bacmafblgmncfagnkdocacfkhjknfeni/contentScript.js:602:36)
    at runSpeech (chrome-extension://bacmafblgmncfagnkdocacfkhjknfeni/contentScript.js:612:8)
    at chrome-extension://bacmafblgmncfagnkdocacfkhjknfeni/contentScript.js:628:7Understand this error
contentScript.js:627 KickSpeech Object
510/:1 Error in event handler: TypeError: Cannot read properties of undefined (reading 'length')
    at WedataConvertTableToLocalConvertDic (chrome-extension://bacmafblgmncfagnkdocacfkhjknfeni/contentScript.js:441:27)
    at CreateConvertDic (chrome-extension://bacmafblgmncfagnkdocacfkhjknfeni/contentScript.js:456:20)
    at SpeechWithPageElementArray (chrome-extension://bacmafblgmncfagnkdocacfkhjknfeni/contentScript.js:505:20)
    at runSpeechWithSiteInfo (chrome-extension://bacmafblgmncfagnkdocacfkhjknfeni/contentScript.js:602:36)
    at runSpeech (chrome-extension://bacmafblgmncfagnkdocacfkhjknfeni/contentScript.js:612:8)
    at chrome-extension://bacmafblgmncfagnkdocacfkhjknfeni/contentScript.js:628:7Understand this error
243Third-party cookie will be blocked in future Chrome versions as part of Privacy Sandbox.

Service Workerの表示
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.Understand this error
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.Understand this error
Unchecked runtime.lastError: The message port closed before a response was received.Understand this error
Unchecked runtime.lastError: The message port closed before a response was received.Understand this error
Unchecked runtime.lastError: The message port closed before a response was received.Understand this error
background.js:188 force update SiteInfo: (4174) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, …]
Unchecked runtime.lastError: The message port closed before a response was received.


speechSynthesis.htmlの表示
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.Understand this error
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.Understand this error
Unchecked runtime.lastError: The message port closed before a response was received.Understand this error
Unchecked runtime.lastError: The message port closed before a response was received.Understand this error
speechSynthesis.js:64 onMessage Object
speechSynthesis.js:64 onMessage Object
Unchecked runtime.lastError: The message port closed before a response was received.Understand this error
speechSynthesis.js:64 onMessage Object
background.js:188 force update SiteInfo: Array(4174)
Unchecked runtime.lastError: The message port closed before a response was received.


という表示が出ていました。

https://ncode.syosetu.com/n7787eq/510/
こちらのページを発話させようとしました。

**Comment by limura** [comment]
確認ありがとうございます。

うわぁすみません。比較条件を書き間違えていました。
4d6074d で修正しましたのでそちらでもう一度試して頂けますと助かります。

**Comment by szk24** [comment]
「開始」ボタンを押したら発話しました。
ありがとうございます。

発話するのですが、chrome://.extensions を見るとTabSpeechの部分にエラーの表示が出ているのですが、これは大丈夫でしょうか？
以下、「エラー」をクリックすると表示される画面

![エラーメッセージ](https://github.com/user-attachments/assets/5bb391ae-b8b9-40e7-b076-c22907cb1253)

**Comment by limura** [comment]
確認ありがとうございます。
やはりそこでよかったのですね。安心しました。
それでは、こちらのものでリリース準備に入ろうと思います。
ただ、今現在は 2.0.5 を審査に出してしまっているので、そちらの審査が終わってからになります。

Extension context invalidated といったものは、拡張機能を読み込み直した後に以前その拡張機能が有効になっていたタブを開くと(そのタブのcontent scriptが動いたりして(その古い方のService Worker向けに)メッセージ送信がされると)発生するエラーなのでとりあえずは気にしないで良いと思います。

**Comment by szk24** [comment]
わかりました。
ありがとうございます。

あの、お礼にAmazonのリンクから2000円のAmazonギフト券を贈ろうとしたのですが（少なくて申し訳ありません）、送り方がわからないのと、在庫切れになっていて贈れず。
別のAmazonギフト券のページから贈ろうとしたのですが、Eメールが必要みたいなのですが、教えてもらう事って可能でしょうか？
Eメールも個人情報になるので、どうしたものかと。
もしくは、YouTubeのスパチャみたいに贈れるようなサイトはお持ちじゃないでしょうか？

**Comment by limura** [comment]
ありがとうございます。
先程 審査が終わったようなので 2.0.6 で審査にかけ直そうと思っています。
ただ、「説明文が短すぎるからなんとかせよ」という理由でrejectされてしまっているので、その辺りを書き加えてからという形になりそうです。
また、ここ最近の審査にかかる時間を見ていると、2,3日はかかりそうなので今週末辺りにならないと 2.0.6 はストアには並ばなそうです。

それと、支援のお話なのですが、お気持ちだけで結構ですよ。
といいますか、ここまでデバッグにお時間を使っていただいた上、問題の解消を確認していただけているので十分に貢献なさっていると思います。ありがとうございます。助かりました。

また何か気づきましたらお知らせください。
よろしくお願いいたします。

**Comment by szk24** [comment]
こちらこそありがとうございました。
TabSpeechがないととても困ってしまうので。
個人的に非常にありがたい拡張機能なのです。

こちらこそ、無償で提供していただいているプログラムのデバッグに時間を割いていただいて、とても感謝しております。
支援はお気持ちだけで・・との事ですが、（こちらの自己満足で申し訳ありませんが、）今回は贈らせていただきますね。
日頃からお世話になっているTabSpeechと開発者様への感謝を込めて。

もし次回から何かありましたら、その際はお気持ちだけ贈らせていただきますね。
ありがとうございました。

**Comment by szk24** [comment]
issueをクローズするのを忘れておりました。
デバッグありがとうございました。

**Comment by limura** [comment]
reject してすぐに審査に提出したのがよかったのか、何故かあっという間に審査が通りました。
ということで chrome://extensions/  辺りから更新するなどで Chromeウェブストア 側のものでも 2.0.6 が使えるようになっています。

**Comment by szk24** [comment]
教えていただきありがとうございます。
